services:
  codeduelplatform:
    image: codeduelplatform
    build:
      context: .
      dockerfile: CodeDuelPlatform/Dockerfile
    depends_on:
      - postgres
      - redis
    environment:
      - ConnectionStrings__DefaultConnection=User ID=postgres;Password=5959;Host=host.docker.internal;Port=5432;Database=testai;
      - ConnectionStrings__RedisConnection=redis:6379,password=redis_password
      - Redis__MatchmakingQueueExpiry=300
      - Redis__ActiveDuelExpiry=3600
    ports:
      - "8080:80"
      - "8081:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    image: frontend-react
    build:
      context: ./frontend-react
      dockerfile: Dockerfile
    depends_on:
      - codeduelplatform
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=5959
      - POSTGRES_DB=testai
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.0-alpine
    command: redis-server --appendonly yes --requirepass redis_password
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  nginx:
    image: nginx:stable-alpine
    ports: 
      - "80:80"
    depends_on:
      - codeduelplatform
      - frontend
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'

volumes:
  postgres_data:
  redis_data:
