services:
  codeduelplatform:
    image: codeduelplatform
    build:
      context: .
      dockerfile: CodeDuelPlatform/Dockerfile
    depends_on:
      - postgres
      - redis
    environment:
      - ConnectionStrings__DefaultConnection=User ID=postgres;Password=5959;Host=postgres;Port=5432;Database=testai;
      - ConnectionStrings__RedisConnection=redis:6379,password=redis_password
      - Redis__MatchmakingQueueExpiry=300
      - Redis__ActiveDuelExpiry=3600
    # Internal ports only
    expose:
      - "80"
      - "443"
    restart: unless-stopped

  frontend:
    image: frontend-react
    build:
      context: ./frontend-react
      dockerfile: Dockerfile
    depends_on:
      - codeduelplatform
    # Internal port only
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./health-check.html:/usr/share/nginx/html/health-check.html:ro
      - ./static-check.html:/usr/share/nginx/html/static-check.html:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - codeduelplatform
      - frontend
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=5959
      - POSTGRES_DB=testai
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7.0-alpine
    command: redis-server --appendonly yes --requirepass redis_password
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
