CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250403132407_InitialCreate') THEN
    CREATE TABLE "Questions" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Text" text NOT NULL,
        "CorrectAnswer" text NOT NULL,
        "Explanation" text NULL,
        "Difficulty" integer NOT NULL,
        "Category" text NOT NULL,
        CONSTRAINT "PK_Questions" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250403132407_InitialCreate') THEN
    CREATE TABLE "Users" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Username" character varying(50) NOT NULL,
        "Email" text NOT NULL,
        "PasswordHash" text NOT NULL,
        "RegistrationDate" timestamp with time zone NOT NULL,
        "TotalWins" integer NOT NULL,
        "TotalLosses" integer NOT NULL,
        "Rating" integer NOT NULL,
        "IsSearchingOpponent" boolean NOT NULL,
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250403132407_InitialCreate') THEN
    CREATE TABLE "Duels" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "FirstUserId" integer NOT NULL,
        "SecondUserId" integer NOT NULL,
        "StartTime" timestamp with time zone NOT NULL,
        "EndTime" timestamp with time zone NULL,
        "WinnerId" integer NULL,
        "IsDraw" boolean NOT NULL,
        "IsCompleted" boolean NOT NULL,
        "FirstUserCorrectAnswers" integer NOT NULL,
        "SecondUserCorrectAnswers" integer NOT NULL,
        CONSTRAINT "PK_Duels" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Duels_Users_FirstUserId" FOREIGN KEY ("FirstUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Duels_Users_SecondUserId" FOREIGN KEY ("SecondUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Duels_Users_WinnerId" FOREIGN KEY ("WinnerId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250403132407_InitialCreate') THEN
    CREATE TABLE "DuelQuestions" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "DuelId" integer NOT NULL,
        "QuestionId" integer NOT NULL,
        "QuestionOrder" integer NOT NULL,
        "FirstUserAnswer" text NOT NULL,
        "SecondUserAnswer" text NOT NULL,
        "IsFirstUserAnswerCorrect" boolean NULL,
        "IsSecondUserAnswerCorrect" boolean NULL,
        "AnswerTime" timestamp with time zone NULL,
        CONSTRAINT "PK_DuelQuestions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_DuelQuestions_Duels_DuelId" FOREIGN KEY ("DuelId") REFERENCES "Duels" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_DuelQuestions_Questions_QuestionId" FOREIGN KEY ("QuestionId") REFERENCES "Questions" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250403132407_InitialCreate') THEN
    CREATE INDEX "IX_DuelQuestions_DuelId" ON "DuelQuestions" ("DuelId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250403132407_InitialCreate') THEN
    CREATE INDEX "IX_DuelQuestions_QuestionId" ON "DuelQuestions" ("QuestionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250403132407_InitialCreate') THEN
    CREATE INDEX "IX_Duels_FirstUserId" ON "Duels" ("FirstUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250403132407_InitialCreate') THEN
    CREATE INDEX "IX_Duels_SecondUserId" ON "Duels" ("SecondUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250403132407_InitialCreate') THEN
    CREATE INDEX "IX_Duels_WinnerId" ON "Duels" ("WinnerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250403132407_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250403132407_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Users_Username" ON "Users" ("Username");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250403132407_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250403132407_InitialCreate', '7.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250429184437_initContainer') THEN
    ALTER TABLE "Duels" ADD "Status" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250429184437_initContainer') THEN
    ALTER TABLE "DuelQuestions" ADD "FirstUserSubmitted" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250429184437_initContainer') THEN
    ALTER TABLE "DuelQuestions" ADD "SecondUserSubmitted" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250429184437_initContainer') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250429184437_initContainer', '7.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250430100513_addNullable') THEN
    ALTER TABLE "DuelQuestions" ALTER COLUMN "SecondUserAnswer" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250430100513_addNullable') THEN
    ALTER TABLE "DuelQuestions" ALTER COLUMN "FirstUserAnswer" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250430100513_addNullable') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250430100513_addNullable', '7.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250604204439_AddQuestionTypes') THEN
    ALTER TABLE "Questions" ADD "BlanksData" jsonb NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250604204439_AddQuestionTypes') THEN
    ALTER TABLE "Questions" ADD "CreatedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250604204439_AddQuestionTypes') THEN
    ALTER TABLE "Questions" ADD "Options" jsonb NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250604204439_AddQuestionTypes') THEN
    ALTER TABLE "Questions" ADD "QuestionType" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250604204439_AddQuestionTypes') THEN
    CREATE INDEX "IX_Questions_BlanksData_GIN" ON "Questions" USING GIN ("BlanksData");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250604204439_AddQuestionTypes') THEN
    CREATE INDEX "IX_Questions_FillBlanks" ON "Questions" ("Id") WHERE "QuestionType" = 3;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250604204439_AddQuestionTypes') THEN
    CREATE INDEX "IX_Questions_Options_GIN" ON "Questions" USING GIN ("Options");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250604204439_AddQuestionTypes') THEN
    CREATE INDEX "IX_Questions_QuestionType" ON "Questions" ("QuestionType");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250604204439_AddQuestionTypes') THEN
    CREATE INDEX "IX_Questions_QuestionType_Category" ON "Questions" ("QuestionType", "Category");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250604204439_AddQuestionTypes') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250604204439_AddQuestionTypes', '7.0.10');
    END IF;
END $EF$;
COMMIT;

